"""Change meeting_date date

Revision ID: 2772ae868e4a
Revises: aff2fd41d846
Create Date: 2024-07-10 15:57:27.126147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2772ae868e4a'
down_revision: Union[str, None] = 'aff2fd41d846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'meeting_date',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
    op.alter_column('transcripts', 'date',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transcripts', 'date',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               nullable=True)
    op.alter_column('files', 'meeting_date',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
    # ### end Alembic commands ###
