"""Add file_path to files

Revision ID: 30506a01e680
Revises: 9d7bc1123242
Create Date: 2024-07-07 00:22:11.157516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30506a01e680'
down_revision: Union[str, None] = '9d7bc1123242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'file_path')
    # ### end Alembic commands ###
